[theme]
primaryColor = "#2563EB"
backgroundColor = "#f6f7f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1E293B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false