[theme]
primaryColor = "#2563EB"
backgroundColor = "#5ea3f3"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false